### ISSUE TITLE
Async function

### ISSUE THREAD

**Issue by xxczaki** [davideicardi/live-plugin-manager#19]
Hi,

I installed an AsyncFunction-returning package. Unfortunately, when I try to use it (via `manager.require(name).default`, it shows `[Function]`, instead of `[AsyncFunction]`.

**Comment by davideicardi** [comment]
Can you provice me a package example to reproduce the problem. Or best of all a unit test..
Thanks!

**Comment by xxczaki** [comment]
@davideicardi Here is my use case:

I have a constructor, which receives an array of async functions (plugins) as an argument. I save a list of files in the storage, from which I install all of them:

```ts
await manager.install('@parsify/date');


// ...


// Plugins storage (names)
const plugins = await store.get('plugins') || [];

// This array gets passed to the constructor
// I think this is why it returns a synchronous function
const pluginsArray = plugins.map((name: string) => manager.require(name).default);

const parsify = new Parsify([
	examplePlugin(),
	...plugins
]);

// Let's say I have just 1 plugin installed (@parsify/date)
console.log(parsify); //=> Parsify { plugins: [ [AsyncFunction], [Function] ] }
```

Here is the code for the package, which I install: https://github.com/parsify-dev/date/blob/master/src/index.ts

As you can see, it exports an async function.

**Comment by xxczaki** [comment]
I found a solution, turns out the problem was my fault:

Instead of:
```js
manager.require(name).default
```

I should have used
```js
manager.require(name).default()
```

This way the actual exported function is fetched :smile:
