### ISSUE TITLE
no such file or directory, mkdir '/plugin_packages'

### ISSUE THREAD

**Issue by WarrenJones** [davideicardi/live-plugin-manager#46]
I was using the plugin in mac and my application was base on electron,and it show such a bug in build mode,dev mode works well

**Comment by WarrenJones** [comment]
Okay it works now after I defined the

**Comment by WarrenJones** [comment]
pluginsPath: path.resolve(app.getPath('userData'), '.plugins'),

**Comment by WarrenJones** [comment]
It's such a gorgeous plugin, stars would comes greate sooner or later!

**Comment by davideicardi** [comment]
Thank you @WarrenJones ! 

Unfortunately with Electron there are some strange issues already reported in the past, like #13 . I don't have a lot of experience with Electron and never tested it properly.
