### ISSUE TITLE
getInfo should load the package from disk

### ISSUE THREAD

**Issue by WarrenJones** [davideicardi/live-plugin-manager#47]
![image](https://user-images.githubusercontent.com/8704779/103967506-1d67f680-519d-11eb-8270-458160a18f95.png)

getInfo now only load from installedPlugins,but the installedPlugins are init as empty array.

**Comment by davideicardi** [comment]
Maybe it is a duplicate of #18 ? Can you explain a little better your problem?

**Comment by WarrenJones** [comment]
> Maybe it is a duplicate of #18 ? Can you explain a little better your problem?

yes,I found it in #18
