### ISSUE TITLE
Proxy settings for NPM registry

### ISSUE THREAD

**Issue by bartenew** [davideicardi/live-plugin-manager#48]
I'm using a private registry that is only available with proxy. Is there a way to setup proxy URL?

**Comment by davideicardi** [comment]
I think that right now it is not possible. But internally this library use `node-fetch` that can be configured with something like [proxy-node-fetch](https://www.scrapingbee.com/blog/proxy-node-fetch/).
We should probably expose this as a configuration (like adding an optional `httpAgent` or similar...).
As usual any PR is appreciated.
