### ISSUE TITLE
Is it not possible to require npm/node packages that are already installed?

### ISSUE THREAD

**Issue by jamesgibson14** [davideicardi/live-plugin-manager#7]
I can install some packages from npm just fine, however when I try to require packages already installed for the app, "util", "vue", etc I get module not found.

**Comment by davideicardi** [comment]
The idea is that you should use `PluginManager.require` just to load plugins. To load modules installed in the host you can just use the standard `require`. Correct?

Also consider that if for example a plugin depends on `vue` and `vue` is already installed on the host process you can require it from within the plugin.
